apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: united-remote
spec:
  selector:
    app: mongodb
    project: multi-group
    tier: db
  ports:
  - protocol: TCP
    port: 27017 #service-port
    targetPort: 27017 #container-port