apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: united-remote
spec:
  type: LoadBalancer
  selector:
    app: app
    project: multi-group
    tier: backend
  ports:
  - protocol: TCP
    port: 5000  # service-port
    targetPort: 5000 # container-port
